# General Jekyll Config
header_pages:
 - about.md
 - Resources.md
highlighter: rouge
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
plugins:
  - jemoji
